import type { EnemyDef, EnemyType } from '../types';

const WALK = ['Walking_A', 'Walking_B', 'Walking_C'];
const RUN = ['Running_A', 'Running_B', ...WALK];
const DEATH = ['Death_A', 'Death_B'];
const HIT = ['Hit_A', 'Hit_B'];

export const ENEMIES: Record<EnemyType, EnemyDef> = {
  basic: {
    type: 'basic',
    name: 'Skeleton',
    model: 'Skeleton_Minion',
    walkClips: WALK,
    deathClips: DEATH,
    hitClips: HIT,
    hp: 55,
    speed: 0.95,
    reward: 8,
    livesCost: 1,
    armor: 0,
    scale: 0.55,
    animSpeedScale: 1.0,
  },
  runner: {
    type: 'runner',
    name: 'Runner',
    model: 'Skeleton_Rogue',
    walkClips: RUN,
    deathClips: DEATH,
    hitClips: HIT,
    hp: 34,
    speed: 1.7,
    reward: 7,
    livesCost: 1,
    armor: 0,
    scale: 0.5,
    animSpeedScale: 1.1,
  },
  armored: {
    type: 'armored',
    name: 'Armored Skeleton',
    model: 'Skeleton_Warrior',
    walkClips: ['Walking_B', ...WALK],
    deathClips: DEATH,
    hitClips: HIT,
    hp: 170,
    speed: 0.6,
    reward: 18,
    livesCost: 1,
    armor: 0.4,
    scale: 0.58,
    animSpeedScale: 0.85,
  },
  captain: {
    type: 'captain',
    name: 'Skeleton Captain',
    model: 'Skeleton_Mage',
    walkClips: WALK,
    deathClips: DEATH,
    hitClips: HIT,
    hp: 240,
    speed: 1.05,
    reward: 32,
    livesCost: 2,
    armor: 0.15,
    scale: 0.66,
    tint: 0xffd27f,
    isElite: true,
    buffRadius: 1.8,
    buffSpeed: 1.1,
    animSpeedScale: 1.0,
  },
  boss: {
    type: 'boss',
    name: 'Skeleton Boss',
    model: 'Skeleton_Warrior',
    walkClips: ['Walking_B', ...WALK],
    deathClips: DEATH,
    hitClips: HIT,
    hp: 2400,
    speed: 0.42,
    reward: 160,
    livesCost: 6,
    armor: 0.25,
    scale: 1.05,
    tint: 0xff8888,
    isBoss: true,
    animSpeedScale: 0.7,
  },
};
